connections = 
{
    /abm_and_smem/abm_and_smem_ctl/S_AXI              bdc/sources_1/bd/abm_and_smem/src/abm_and_smem_ctl.v REG 
    /adc_bank/axi_adc_bank/S_AXI    
    /packet_generator/poke/poke_ctl/S_AXI
    /packet_generator/transmit/abm_send_ctl/S_AXI
    /chip_power/indy_power_ctl/S_AXI
    /packet_generator/load_from_host_ram/test_abm_ctl/S_AXI
    /abm_and_smem/chipif_cdc/clock_manager/clock_mgr_ctl/S_AXI
}
