//=====================================================
// This file was auto-generated by xlate_vreg v1.2
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    REG_LOAD_ABM_VIA_PCI
// Size:        32-bits
// Description: Copy an ABM from host-RAM into one or both ABM buffers
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     load_0                         1       0 WO   n/a         Copy ABM from host RAM to ABM buffer #0
//     load_1                         1       1 WO   n/a         Copy ABM from host RAM to ABM buffer #0
//
#define REG_LOAD_ABM_VIA_PCI                                         0x0000000000001000ULL
#define REG_LOAD_ABM_VIA_PCI_load_0                                  0x0100000000001000ULL
#define REG_LOAD_ABM_VIA_PCI_load_1                                  0x0101000000001000ULL


//
// Register:    REG_ABM_PCI_SRC_ADDR
// Size:        64-bits
// Description: Source address in host RAM for loading ABMs
//
#define REG_ABM_PCI_SRC_ADDR                                         0x4000000000001004ULL


//
// Register:    REG_SELECT_HSI
// Size:        32-bits
// Description: Select HSI or SPI bus for SMEM writes
//              0 = SPI, 1 = HSI
//
#define REG_SELECT_HSI                                               0x000000000000100cULL


//
// Register:    REG_FORCE_SMEM
// Size:        32-bits
// Description: A rising edge = all rows of the next received ABM
//              will be written to cache and SMEM
//              Rising edge sensitive:  write a 0 then a 1
//
#define REG_FORCE_SMEM                                               0x0000000000001010ULL


//
// Register:    REG_CHIPIO_ADDR
// Size:        32-bits
// Description: The address on the sensor chip that you wish to read or write
//
#define REG_CHIPIO_ADDR                                              0x0000000000001014ULL


//
// Register:    REG_CHIPIO_DATA
// Size:        32-bits
// Description: Reading this register reads the sensor-chip address specified
//              by CHIPIO_ADDR
//              
//              Writing to this register writes to the sensor-chip address
//              specified by CHIPIO_ADDR
//
#define REG_CHIPIO_DATA                                              0x0000000000001018ULL


//
// Register:    REG_CHIPIO_DATA_INCR
// Size:        32-bits
// Description: Reading this register reads the sensor-chip address specified
//              by CHIPIO_ADDR, then adds 4 to CHIPIO_ADDR
//              
//              Writing to this register writes to the sensor-chip address
//              specified by CHIPIO_ADDR then adds 4 to CHIPIO_ADDR
//
#define REG_CHIPIO_DATA_INCR                                         0x000000000000101cULL


//
// Register:    REG_SMEM_BUSY
// Size:        32-bits
// Description: Non-zero = SMEM is being updated
//              Read-only
//
#define REG_SMEM_BUSY                                                0x0000000000001024ULL


//
// Register:    REG_SMEM_ROWS_UPD
// Size:        32-bits
// Description: The count of rows updated during the last SMEM update
//              Read-only
//
#define REG_SMEM_ROWS_UPD                                            0x0000000000001028ULL


//
// Register:    REG_SMEM_WORDS_UPD
// Size:        32-bits
// Description: The count of 32-bit words updated during the last SMEM update
//              Read-only
//
#define REG_SMEM_WORDS_UPD                                           0x000000000000102cULL


//
// Register:    REG_ABM_COUNT
// Size:        32-bits
// Description: The count of ABMs received.  Write any value to clear
//
#define REG_ABM_COUNT                                                0x0000000000001030ULL


//
// Register:    REG_HS_CLK_REF
// Size:        32-bits
// Description: HSI clock: reference frequency in Hz.
//              Read-only
//
#define REG_HS_CLK_REF                                               0x0000000000001040ULL


//
// Register:    REG_HS_CLK_VCO
// Size:        32-bits
// Description: HSI clock - VCO configuration.  See "Clock Configuration Register 0" in PG065.
//              Read-only
//              
//              >                 HS_CLK_REF * (clkfbout_mlt + clkfbout_frac/1000)
//              > VCO frequency = ------------------------------------------------
//              >                                 divclk_divide
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     divclk_divide                  8   07:00 RO   n/a         8-bit divide value of the reference clock
//     clkfbout_mult                  8   15:08 RO   n/a         Integer part of clock multiplier
//     clkfbout_frac                  10  25:16 RO   n/a         Fractional part of clock multiplier
//
#define REG_HS_CLK_VCO                                               0x0000000000001044ULL
#define REG_HS_CLK_VCO_divclk_divide                                 0x0800000000001044ULL
#define REG_HS_CLK_VCO_clkfbout_mult                                 0x0808000000001044ULL
#define REG_HS_CLK_VCO_clkfbout_frac                                 0x0a10000000001044ULL


//
// Register:    REG_HS_CLK_DIV
// Size:        32-bits
// Description: HSI clock - Frequency divider.  See "Clock Configuration Register 2" in PG065
//              ** Changing this value changes the frequency of the HSI clock! **
//              
//              >                                   VCO frequency
//              > HSI clock frequency = ------------------------------------
//              >                       (clkout_divide + clockout_frac/1000)
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     clkout_divide                  8   07:00 RW   n/a         Integer portion of VCO divide value
//     clkout_frac                    10  17:08 RW   n/a         Fractional portion of VCO divide value
//
#define REG_HS_CLK_DIV                                               0x0000000000001048ULL
#define REG_HS_CLK_DIV_clkout_divide                                 0x0800000000001048ULL
#define REG_HS_CLK_DIV_clkout_frac                                   0x0a08000000001048ULL


//
// Register:    REG_HS_CLK_FREQ
// Size:        32-bits
// Description: The measured value of the HSI clock, in Hz
//              Read-only
//
#define REG_HS_CLK_FREQ                                              0x000000000000104cULL



#endif
